spring:
  application:
    name: ergon-control-plane
  datasource:
    url: ${ERGON_DATABASE_URL}
    username: ${ERGON_DATABASE_USERNAME}
    password: ${ERGON_DATABASE_PASSWORD}
  flyway:
    table: ergon_flyway_schema_history
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ERGON_HUMAN_JWT_ISSUER_URI:}

ergon:
  security:
    human-jwt:
      identity-provider: ${ERGON_HUMAN_IDENTITY_PROVIDER:}

server:
  port: 8090
